-- System activity seed (generated from src/data/seed-activities.ts)
-- Regenerate: npm run seed:sql
-- Core engine types are inserted first so Listening/Writing/etc. still load even if
-- media types (music/video/game) are rejected by an older CHECK constraint.

delete from public.activities where is_system = true;

-- Core skills (listening, speaking, writing, reading, grammar, vocabulary, …)
insert into public.activities (
  id, title, description, type, level, difficulty, instructions, content,
  audio_url, image_url, duration, points, is_published, is_system, created_by
) values
(
  gen_random_uuid(),
  'Boardroom Brief',
  'Listen to a short executive update and catch precise details.',
  'listening',
  'C1',
  'hard',
  'Play the audio, then answer all questions.',
  '{"subtype":"comprehension","audioText":"Good morning. Q3 revenue rose twelve percent, driven by enterprise renewals. However, churn in the starter plan remains elevated at six point four percent. Marketing will pause paid social next week while we rebuild the onboarding funnel. Please review the revised forecast by Friday noon.","transcript":"Good morning. Q3 revenue rose twelve percent, driven by enterprise renewals. However, churn in the starter plan remains elevated at six point four percent. Marketing will pause paid social next week while we rebuild the onboarding funnel. Please review the revised forecast by Friday noon.","questions":[{"question":"What happened to Q3 revenue?","options":["It rose 12%","It fell 12%","It stayed flat","It doubled"],"correctIndex":0},{"question":"What drove the revenue change?","options":["Enterprise renewals","Retail walk-ins","Ticket sales","Rent cuts"],"correctIndex":0},{"question":"Starter-plan churn is…","options":["6.4%","12%","Zero","Unknown"],"correctIndex":0},{"question":"What will Marketing pause?","options":["Paid social","Hiring","Payroll","Office Wi-Fi"],"correctIndex":0},{"question":"Why pause paid social?","options":["Rebuild onboarding funnel","Buy new laptops","Close the office","Change the logo"],"correctIndex":0},{"question":"When is the forecast due?","options":["Friday noon","Monday morning","Next month","Tonight"],"correctIndex":0},{"question":"The tone of the brief is…","options":["Professional and urgent","Casual and joking","Angry","Confused"],"correctIndex":0},{"question":"“Churn” here means…","options":["Customers leaving","New hires","Extra bonuses","Office snacks"],"correctIndex":0}]}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&q=80&auto=format&fit=crop',
  12,
  20,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'Podcast: Tiny Habits',
  'A friendly podcast tip about building habits.',
  'listening',
  'B2',
  'hard',
  'Listen once for gist, again for details.',
  '{"subtype":"comprehension","audioText":"Welcome back. Today''s tip is simple: attach a new habit to something you already do. After you pour coffee, write one sentence in your journal. Keep it tiny so your brain doesn''t fight you. Consistency beats intensity every single time.","transcript":"Welcome back. Today''s tip is simple: attach a new habit to something you already do. After you pour coffee, write one sentence in your journal. Keep it tiny so your brain doesn''t fight you. Consistency beats intensity every single time.","questions":[{"question":"What should you attach a new habit to?","options":["Something you already do","A random app","A vacation","A stranger"],"correctIndex":0},{"question":"The coffee example is followed by…","options":["Writing one journal sentence","Running 10km","Buying gear","Calling a coach"],"correctIndex":0},{"question":"Why keep the habit tiny?","options":["So your brain doesn''t fight you","To impress others","To waste time","To skip days"],"correctIndex":0},{"question":"What beats intensity?","options":["Consistency","Luck","Noise","Speed alone"],"correctIndex":0},{"question":"The speaker’s tone is…","options":["Encouraging","Rude","Sarcastic only","Angry"],"correctIndex":0},{"question":"This advice is mainly about…","options":["Habit building","Cooking coffee","Buying journals","Deleting apps"],"correctIndex":0}]}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=800&q=80&auto=format&fit=crop',
  10,
  20,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'Renting a Flat Call',
  'A phone call about viewing an apartment.',
  'listening',
  'B1',
  'medium',
  'Note times, prices, and conditions.',
  '{"subtype":"dialogue","audioText":"Hi, I''m calling about the two-bedroom flat on River Street. Is it still available? Yes, it is. The rent is nine hundred and fifty a month, plus bills. You can view it tomorrow at four. Please bring ID. Perfect, see you then.","transcript":"Hi, I''m calling about the two-bedroom flat on River Street. Is it still available? Yes, it is. The rent is nine hundred and fifty a month, plus bills. You can view it tomorrow at four. Please bring ID. Perfect, see you then.","questions":[{"question":"How many bedrooms?","options":["Two","One","Three","Studio only"],"correctIndex":0},{"question":"Where is the flat?","options":["River Street","Park Avenue","Airport Road","Hill Lane"],"correctIndex":0},{"question":"Is it available?","options":["Yes","No","Only next year","Sold"],"correctIndex":0},{"question":"Monthly rent?","options":["950","450","1950","95"],"correctIndex":0},{"question":"Rent includes bills?","options":["No — plus bills","Yes, all included","Only water","Free forever"],"correctIndex":0},{"question":"Viewing time?","options":["Tomorrow at 4","Today at noon","Friday at 9","Never"],"correctIndex":0},{"question":"What should they bring?","options":["ID","A sofa","A cat only","Cash for the whole year"],"correctIndex":0}]}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80&auto=format&fit=crop',
  10,
  15,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'My Morning Routine',
  'A simple talk about a weekday morning.',
  'listening',
  'A2',
  'easy',
  'Listen for times and actions.',
  '{"subtype":"comprehension","audioText":"I wake up at seven. I take a shower, then I have toast and coffee. I leave home at eight and take the bus to work. In the evening I cook dinner and watch a short show.","transcript":"I wake up at seven. I take a shower, then I have toast and coffee. I leave home at eight and take the bus to work. In the evening I cook dinner and watch a short show.","questions":[{"question":"Wake-up time?","options":["7:00","8:00","6:00","9:00"],"correctIndex":0},{"question":"Breakfast includes…","options":["Toast and coffee","Pizza","Soup only","Nothing"],"correctIndex":0},{"question":"Leave home at…","options":["8:00","7:00","Noon","Midnight"],"correctIndex":0},{"question":"How do they go to work?","options":["By bus","By plane","By boat","Walk forever"],"correctIndex":0},{"question":"Evening activity?","options":["Cook and watch a show","Go to the gym only","Sleep at 5","Fly abroad"],"correctIndex":0},{"question":"First action after waking?","options":["Take a shower","Go to work","Watch TV","Call the boss"],"correctIndex":0}]}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1516280440614-6697288d5d38?w=800&q=80&auto=format&fit=crop',
  8,
  10,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'At the Café',
  'A short café order in clear, slow English.',
  'listening',
  'A1',
  'easy',
  'Listen once. Then answer — one skill per question.',
  '{"subtype":"dialogue","audioText":"Hello! I''d like a large tea and a cheese sandwich, please. No sugar in the tea. That''s six dollars. Thank you!","transcript":"Hello! I''d like a large tea and a cheese sandwich, please. No sugar in the tea. That''s six dollars. Thank you!","questions":[{"question":"What size drink?","options":["Large","Small","Medium","No drink"],"correctIndex":0,"explanation":"The customer says “a large tea”."},{"question":"What do they drink?","options":["Tea","Coffee","Juice","Water only"],"correctIndex":0},{"question":"What food?","options":["Cheese sandwich","Pizza","Salad","Cake"],"correctIndex":0},{"question":"Sugar in the tea?","options":["No","Yes, a lot","Honey only","Unknown"],"correctIndex":0,"explanation":"They say “No sugar in the tea.”"},{"question":"How much is it?","options":["Six dollars","Sixteen dollars","Free","Sixty dollars"],"correctIndex":0}]}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80&auto=format&fit=crop',
  5,
  10,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'Drama Club: Inversion',
  'Fix theatrical lines using inversion and emphasis.',
  'grammar',
  'C1',
  'hard',
  'Choose the most natural advanced form.',
  '{"prompt":"Advanced grammar in context","questions":[{"question":"Director: “_____ had we started when the lights failed.”","options":["Hardly","Hard","Harder","Hardest"],"correctIndex":0,"explanation":"Hardly had + past perfect."},{"question":"Actor: “_____ I known, I would have brought a spare mic.”","options":["Had","Have","Did","Would"],"correctIndex":0},{"question":"“Not only _____ she forget the line, she also laughed.”","options":["did","does","do","doing"],"correctIndex":0},{"question":"“Rarely _____ such a quiet audience.”","options":["have we seen","we have seen","we saw have","seen we have"],"correctIndex":0},{"question":"Choose the cleft: “_____ the costume that saved the scene.”","options":["It was","It were","There was","It be"],"correctIndex":0},{"question":"“Were it not _____ your tip, I’d still be lost.”","options":["for","to","of","by"],"correctIndex":0},{"question":"Which is correct emphasis?","options":["Never have I been so nervous","Never I have been so nervous","I never have been so nervous never","Have never I been so nervous"],"correctIndex":0},{"question":"“So rare _____ this chance that we booked it.”","options":["was","were","be","been"],"correctIndex":0}]}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&q=80&auto=format&fit=crop',
  12,
  20,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'Office Chat: Conditionals',
  'Pick the right conditional in workplace chats.',
  'grammar',
  'B2',
  'hard',
  'Read the chat bubble and choose the best form.',
  '{"prompt":"Conditionals at work","questions":[{"question":"“If the client _____ late again, we’ll reschedule.”","options":["is","will be","would be","were being"],"correctIndex":0,"explanation":"First conditional: if + present, will + verb."},{"question":"“If I _____ you, I’d send the deck tonight.”","options":["were","am","be","was being"],"correctIndex":0,"explanation":"Second conditional often uses were for all persons."},{"question":"“If we _____ earlier, we wouldn’t be rushing.”","options":["had started","start","would start","starts"],"correctIndex":0,"explanation":"Third conditional: if + past perfect."},{"question":"“Unless she _____, we can’t publish.”","options":["approves","approve","will approve","approving"],"correctIndex":0,"explanation":"Unless = if not; use present after unless here."},{"question":"“I wish the printer _____ working.”","options":["were","is","be","will"],"correctIndex":0,"explanation":"Wish + past for present unreal situations."},{"question":"Zero conditional: “If ice _____, it melts.”","options":["heats","will heat","heated","heating"],"correctIndex":0,"explanation":"Facts: if + present, present."},{"question":"“_____ it rain, the picnic moves indoors.” (formal)","options":["Should","Would","Might","Can"],"correctIndex":0,"explanation":"Should + subject = formal if."},{"question":"Mixed: “If I had saved more, I _____ less stressed now.”","options":["would be","will be","am","was"],"correctIndex":0,"explanation":"Past condition → present result: would + verb."}]}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&q=80&auto=format&fit=crop',
  10,
  20,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'Detective Notes: Present Perfect',
  'Solve clue cards with present perfect vs past simple.',
  'grammar',
  'B1',
  'medium',
  'Choose the form that fits the timeline.',
  '{"prompt":"Present perfect detective","questions":[{"question":"Clue: “Someone _____ the window.” (result still visible)","options":["has broken","broke yesterday only forever","breaking","break"],"correctIndex":0},{"question":"“I _____ three witnesses today.”","options":["have interviewed","interview","am interview","interviewing always"],"correctIndex":0},{"question":"Finished time: “She _____ the file last night.”","options":["closed","has closed","have closed","closing"],"correctIndex":0},{"question":"“_____ you ever _____ a fake ID?”","options":["Have / seen","Did / see ever always","Are / seeing","Do / saw"],"correctIndex":0},{"question":"“He hasn’t arrived _____.”","options":["yet","already yesterday","never last year","ago"],"correctIndex":0},{"question":"“They _____ here since Monday.”","options":["have been","are being","was","be"],"correctIndex":0},{"question":"Wrong pair?","options":["I have saw him","I have seen him","She has gone","We have finished"],"correctIndex":0,"explanation":"“Have saw” is incorrect."},{"question":"“Just” often pairs with…","options":["present perfect","future only","imperative only","gerund only"],"correctIndex":0}]}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&q=80&auto=format&fit=crop',
  10,
  15,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'Picnic Story: Past Simple',
  'Complete a funny picnic story with past forms.',
  'grammar',
  'A2',
  'easy',
  'Choose the correct past simple verb.',
  '{"prompt":"Past simple picnic","questions":[{"question":"Yesterday we _____ to the park.","options":["went","go","goed","going"],"correctIndex":0},{"question":"Maya _____ sandwiches.","options":["made","maked","make","making"],"correctIndex":0},{"question":"The dog _____ the cake!","options":["ate","eated","eat","eats"],"correctIndex":0},{"question":"We _____ very loud.","options":["laughed","laugh","laughs","laughing"],"correctIndex":0},{"question":"It _____ sunny all afternoon.","options":["was","were","is","be"],"correctIndex":0},{"question":"Negative: “We _____ stay late.”","options":["didn''t","doesn''t","don''t","isn''t"],"correctIndex":0},{"question":"Question: “_____ you see the ant parade?”","options":["Did","Do","Does","Are"],"correctIndex":0}]}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800&q=80&auto=format&fit=crop',
  8,
  10,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'Superheroes: Verb To Be',
  'Introduce silly heroes with am/is/are.',
  'grammar',
  'A1',
  'easy',
  'Pick am, is, or are.',
  '{"prompt":"Verb to be","questions":[{"question":"I _____ Caped Banana.","options":["am","is","are","be"],"correctIndex":0},{"question":"She _____ very fast.","options":["is","am","are","be"],"correctIndex":0},{"question":"They _____ best friends.","options":["are","is","am","be"],"correctIndex":0},{"question":"He _____ not lazy.","options":["is","am","are","be"],"correctIndex":0},{"question":"_____ you ready?","options":["Are","Is","Am","Be"],"correctIndex":0},{"question":"We _____ in the city.","options":["are","is","am","be"],"correctIndex":0},{"question":"It _____ a quiet night.","options":["is","are","am","be"],"correctIndex":0}]}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1427504494785-3a9ca7044f45?w=800&q=80&auto=format&fit=crop',
  7,
  10,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'Word Stress: Photography',
  'Pronunciation Lab: Word stress.',
  'pronunciation',
  'B2',
  'hard',
  'Listen → record → compare.',
  '{"text":"Photography is interesting when the light is perfect.","tips":"Stress pho-TOG-ra-phy (second syllable). Keep “interesting” rhythmic.","focus":"Word stress"}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=800&q=80&auto=format&fit=crop',
  6,
  20,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'I Thought It Was Better',
  'Pronunciation Lab: TH sound.',
  'pronunciation',
  'B1',
  'medium',
  'Listen → record → compare.',
  '{"text":"I thought it was better.","tips":"Tongue between teeth for “thought” and a soft “th” feel — not “tought”.","focus":"TH sound"}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1556761175-b413da4baf72?w=800&q=80&auto=format&fit=crop',
  6,
  15,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'Past -ed: Wanted',
  'Pronunciation Lab: Past -ed endings.',
  'pronunciation',
  'A2',
  'easy',
  'Listen → record → compare.',
  '{"text":"I wanted to ask about yesterday’s meeting.","tips":"“Wanted” = want-ed (extra syllable). Don’t swallow the ending.","focus":"Past -ed endings"}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1543269865-cbf427effbad?w=800&q=80&auto=format&fit=crop',
  6,
  10,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'Schwa in Banana',
  'Pronunciation Lab: Schwa sound.',
  'pronunciation',
  'A2',
  'easy',
  'Listen → record → compare.',
  '{"text":"I need a banana and some butter.","tips":"Unstressed vowels often sound like /ə/: ba-NA-na.","focus":"Schwa sound"}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=800&q=80&auto=format&fit=crop',
  6,
  10,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'TH Warm-up',
  'Pronunciation Lab: TH sound.',
  'pronunciation',
  'A1',
  'easy',
  'Listen → record → compare.',
  '{"text":"This thin thing is for you.","tips":"Voice on for “this”; gentle airflow for “thin/thing”.","focus":"TH sound"}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=800&q=80&auto=format&fit=crop',
  6,
  10,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'Nuance: Soft vs Sharp',
  'Choose the word with the right emotional tone.',
  'vocabulary',
  'C1',
  'hard',
  'Pick the best fit for tone.',
  '{"word":"nuance","question":"Vocabulary in context","options":["a","b","c","d"],"correctIndex":0,"questions":[{"question":"A polite disagreement: “I _____ with that approach.”","options":["respectfully disagree","hate forever","scream about","delete"],"correctIndex":0},{"question":"Softer than “angry”:","options":["irritated","furious","enraged","livid"],"correctIndex":0},{"question":"Business: “Let’s _____ the timeline.”","options":["revisit","destroy","ignore","explode"],"correctIndex":0},{"question":"Formal thank-you:","options":["I appreciate your help","Thx lol","Whatever","K"],"correctIndex":0},{"question":"“Mitigate” means roughly…","options":["reduce","increase","celebrate","invent"],"correctIndex":0},{"question":"Opposite of “vague”:","options":["precise","fuzzy","messy","random"],"correctIndex":0},{"question":"“Albeit” is closest to…","options":["although","because","never","yesterday"],"correctIndex":0},{"question":"Collocation: “raise a _____.”","options":["concern","elephant","pizza","cloud"],"correctIndex":0}]}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&q=80&auto=format&fit=crop',
  10,
  20,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'Daily Phrasal Verbs',
  'Common phrasals in everyday scenes.',
  'vocabulary',
  'B1',
  'medium',
  'Choose the phrasal that fits.',
  '{"word":"phrasal verbs","question":"Phrasals","options":["a","b","c","d"],"correctIndex":0,"questions":[{"question":"Please _____ the form.","options":["fill in","fill under","fill off","fill away"],"correctIndex":0},{"question":"I’ll _____ you tomorrow.","options":["call back","call under","call off to","call into pizza"],"correctIndex":0},{"question":"She _____ smoking last year.","options":["gave up","gave under","gave across","gave into night"],"correctIndex":0},{"question":"_____ the lights, please.","options":["Turn off","Turn under","Turn of","Turn into"],"correctIndex":0},{"question":"We need to _____ the mess.","options":["clean up","clean under","clean off to","clean into"],"correctIndex":0},{"question":"“Look after” means…","options":["take care of","look for keys only","ignore","shout"],"correctIndex":0},{"question":"The meeting was _____.","options":["put off","put under","put eating","put sky"],"correctIndex":0}]}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&q=80&auto=format&fit=crop',
  10,
  15,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'Travel Words Pack',
  'Airport and hotel words you’ll actually use.',
  'vocabulary',
  'A2',
  'easy',
  'Match meaning to context.',
  '{"word":"boarding pass","question":"Travel vocab","options":["a","b","c","d"],"correctIndex":0,"questions":[{"question":"You show this at the gate:","options":["boarding pass","menu","umbrella","receipt for socks"],"correctIndex":0},{"question":"Place to sleep on a trip:","options":["hotel","passport","gate","runway"],"correctIndex":0},{"question":"Bags go to…","options":["baggage claim","classroom","kitchen","library"],"correctIndex":0},{"question":"“Departure” means…","options":["leaving","arriving forever","eating","sleeping"],"correctIndex":0},{"question":"Document with your photo for travel:","options":["passport","napkin","ticket stub only always","keychain"],"correctIndex":0},{"question":"“Window seat” is…","options":["next to the window","in the bathroom","outside the plane","a café chair only"],"correctIndex":0}]}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=800&q=80&auto=format&fit=crop',
  8,
  10,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'Food & Feelings',
  'Basic words for meals and moods.',
  'vocabulary',
  'A1',
  'easy',
  'Choose the best word.',
  '{"word":"hungry","question":"Basics","options":["a","b","c","d"],"correctIndex":0,"questions":[{"question":"I want food. I’m…","options":["hungry","angry","angry","tall"],"correctIndex":0},{"question":"Morning meal:","options":["breakfast","suitcase","ticket","cloud"],"correctIndex":0},{"question":"Opposite of sad:","options":["happy","angry","heavy","late"],"correctIndex":0},{"question":"Drink that is hot and brown:","options":["coffee","shoe","pencil","door"],"correctIndex":0},{"question":"“Thirsty” means you want…","options":["water","a map","a coat","a song"],"correctIndex":0}]}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1546410531-bb4caa50b06b?w=800&q=80&auto=format&fit=crop',
  7,
  10,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'Business Collocations',
  'Natural word partners for work English.',
  'vocabulary',
  'B2',
  'hard',
  'Pick the natural collocation.',
  '{"word":"collocation","question":"Business pairs","options":["a","b","c","d"],"correctIndex":0,"questions":[{"question":"_____ a meeting","options":["Hold","Cook","Wear","Paint"],"correctIndex":0},{"question":"_____ a deadline","options":["Meet","Eat","Sing","Drive"],"correctIndex":0},{"question":"_____ feedback","options":["Give","Bake","Swim","Fly"],"correctIndex":0},{"question":"_____ an email","options":["Send","Drink","Wear","Plant"],"correctIndex":0},{"question":"_____ progress","options":["Make","Break glass only","Sleep","Jump"],"correctIndex":0},{"question":"_____ a contract","options":["Sign","Fry","Knit","Whistle"],"correctIndex":0},{"question":"Heavy _____ of emails","options":["volume","pizza","socks","clouds"],"correctIndex":0}]}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=800&q=80&auto=format&fit=crop',
  10,
  20,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'Urban Mobility Debate',
  'Read a short opinion piece on city transport.',
  'reading',
  'C1',
  'hard',
  'Read carefully, then answer.',
  '{"passage":"Cities that expand bike lanes often face loud pushback from drivers, yet data from several European capitals shows shorter average commute times within two years. The trade-off is political, not merely technical: councils must decide whether street space serves throughput of cars or access for more people.","question":"Main idea?","options":["Bike lanes involve political trade-offs but can improve commute times","Cars should always win","Bikes are illegal","Councils never decide anything"],"correctIndex":0,"questions":[{"question":"What do some European cities report after bike lanes?","options":["Shorter commute times","No change ever","Only more accidents forever","Closed cities"],"correctIndex":0},{"question":"Pushback mainly comes from…","options":["Drivers","Fish","Astronauts","Chefs only"],"correctIndex":0},{"question":"The trade-off is described as…","options":["Political","Impossible","Funny only","About dessert"],"correctIndex":0},{"question":"Street space decision is about…","options":["Cars vs access for more people","Only flower pots","Airport runways","Museum tickets"],"correctIndex":0},{"question":"Tone of the passage?","options":["Analytical","Joke-only","Recipe","Sports score"],"correctIndex":0},{"question":"“Throughput” here relates to…","options":["Flow of cars","Cooking oil","Wi-Fi passwords","Shoe sizes"],"correctIndex":0}]}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800&q=80&auto=format&fit=crop',
  12,
  20,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'Article: Sleep Tips',
  'A short health article with clear takeaways.',
  'reading',
  'B1',
  'medium',
  'Find the main idea and details.',
  '{"passage":"Researchers say sleeping seven to eight hours can improve memory and mood. Simple routines help: dim lights an hour before bed, avoid heavy meals late, and keep phones outside the bedroom if you can.","question":"Main tip?","options":["Sleep 7–8 hours and use simple routines","Never sleep","Eat more at midnight","Only use phones in bed"],"correctIndex":0,"questions":[{"question":"Recommended sleep length?","options":["7–8 hours","2 hours","14 hours","No sleep"],"correctIndex":0},{"question":"Benefits mentioned?","options":["Memory and mood","Taller height overnight","Free money","New shoes"],"correctIndex":0},{"question":"Before bed, dim…","options":["Lights","The fridge forever","Your shoes","The sky"],"correctIndex":0},{"question":"Heavy meals late are…","options":["Best avoided","Required","A sport","Illegal everywhere"],"correctIndex":0},{"question":"Phones tip?","options":["Keep outside bedroom if possible","Must sleep with three phones","Call strangers","Delete English"],"correctIndex":0}]}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&q=80&auto=format&fit=crop',
  10,
  15,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'City Guide: Riverside',
  'A friendly tourist paragraph.',
  'reading',
  'A2',
  'easy',
  'Scan for facts.',
  '{"passage":"Welcome to Riverside. Visit the old bridge in the morning, try local coffee near the market, and walk along the river at sunset. Museums are free on the first Sunday of each month.","question":"When are museums free?","options":["First Sunday each month","Every night","Never","Only in December forever"],"correctIndex":0,"questions":[{"question":"Visit the bridge…","options":["In the morning","At midnight only","Never","By helicopter only"],"correctIndex":0},{"question":"Try coffee near the…","options":["Market","Airport runway","Desert","Moon"],"correctIndex":0},{"question":"Walk along the river…","options":["At sunset","Underwater","In a plane","In silence forever only"],"correctIndex":0},{"question":"Museums free on…","options":["First Sunday","Every Tuesday at 3am","Random Wednesdays","Never"],"correctIndex":0}]}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800&q=80&auto=format&fit=crop',
  8,
  10,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'Classroom Notice',
  'Read a simple school notice.',
  'reading',
  'A1',
  'easy',
  'Find the key information.',
  '{"passage":"Notice: English club meets on Friday at 4pm in Room 12. Bring a notebook. New students are welcome!","question":"When is the club?","options":["Friday at 4pm","Monday at 8am","Sunday midnight","Never"],"correctIndex":0,"questions":[{"question":"Room number?","options":["12","1200","2","0"],"correctIndex":0},{"question":"Bring a…","options":["Notebook","Fridge","Bicycle only","Passport always"],"correctIndex":0},{"question":"New students are…","options":["Welcome","Banned","Invisible","Teachers"],"correctIndex":0},{"question":"Subject of the club?","options":["English","Cooking cars","Silent chess only","Space travel"],"correctIndex":0}]}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=800&q=80&auto=format&fit=crop',
  6,
  10,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'Product Review: Headphones',
  'A short customer review with pros and cons.',
  'reading',
  'B2',
  'hard',
  'Identify opinion vs fact.',
  '{"passage":"I bought these headphones for long flights. Battery life is excellent—about thirty hours—but the headband feels tight after two hours. Noise cancelling is strong on engines, weaker on voices. For the price, I’d buy them again.","question":"Overall verdict?","options":["Would buy again despite a tight headband","Hates everything","Never flew","Battery lasts 2 minutes"],"correctIndex":0,"questions":[{"question":"Battery life claimed?","options":["~30 hours","30 minutes","3 hours","Unknown forever"],"correctIndex":0},{"question":"Problem after two hours?","options":["Tight headband","No sound","Explodes","Changes color"],"correctIndex":0},{"question":"Noise cancelling stronger on…","options":["Engines","Voices","Birds only","Silence"],"correctIndex":0},{"question":"Use case mentioned?","options":["Long flights","Cooking","Swimming","Gardening"],"correctIndex":0},{"question":"Would buy again?","options":["Yes","No","Maybe never said","Only if free"],"correctIndex":0}]}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=800&q=80&auto=format&fit=crop',
  10,
  20,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'Argument: AI at Work',
  'Guided writing practice with a clear task.',
  'writing',
  'C1',
  'hard',
  'Write within the word limits.',
  '{"prompt":"Write a short argument: Should companies limit AI tools at work? Give 2 reasons and a clear conclusion.","minWords":120,"maxWords":220,"taskType":"essay"}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1455390582262-044cdead168a?w=800&q=80&auto=format&fit=crop',
  15,
  20,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'Complaint Email',
  'Guided writing practice with a clear task.',
  'writing',
  'B1',
  'medium',
  'Write within the word limits.',
  '{"prompt":"Write an email to a hotel about a noisy room. Be polite but clear. Ask for a solution.","minWords":80,"maxWords":160,"taskType":"short"}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=800&q=80&auto=format&fit=crop',
  15,
  15,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'Email to a Friend',
  'Guided writing practice with a clear task.',
  'writing',
  'A2',
  'easy',
  'Write within the word limits.',
  '{"prompt":"Write a short email to a friend about your weekend plans. Include greeting and closing.","minWords":50,"maxWords":120,"taskType":"short"}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=800&q=80&auto=format&fit=crop',
  15,
  10,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'About Yourself',
  'Guided writing practice with a clear task.',
  'writing',
  'A1',
  'easy',
  'Write within the word limits.',
  '{"prompt":"Write 5–8 sentences about yourself: name, city, work/study, and one hobby.","minWords":40,"maxWords":100,"taskType":"short"}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1456324504439-367cee3b3c32?w=800&q=80&auto=format&fit=crop',
  15,
  10,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'Cover Letter Draft',
  'Guided writing practice with a clear task.',
  'writing',
  'B2',
  'hard',
  'Write within the word limits.',
  '{"prompt":"Draft a short cover letter for an English-speaking internship. Mention skills and motivation.","minWords":100,"maxWords":180,"taskType":"essay"}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1517842645767-c639042777db?w=800&q=80&auto=format&fit=crop',
  15,
  20,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'Career Pitch (1 min)',
  'Speaking practice with a clear prompt.',
  'speaking',
  'B2',
  'hard',
  'Record when ready.',
  '{"prompt":"Speak for about one minute: your future career, skills, and one challenge you’ll prepare for.","expectedDuration":60,"mode":"answer","evaluation":{"pronunciation":true,"fluency":true,"grammar":true,"vocabulary":true,"coherence":true}}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=800&q=80&auto=format&fit=crop',
  10,
  20,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'Last Vacation',
  'Speaking practice with a clear prompt.',
  'speaking',
  'B1',
  'medium',
  'Record when ready.',
  '{"prompt":"Describe your last vacation: where, who with, and one funny moment.","expectedDuration":60,"mode":"answer","evaluation":{"pronunciation":true,"fluency":true,"grammar":true,"vocabulary":true,"coherence":true}}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1556761175-b413da4baf72?w=800&q=80&auto=format&fit=crop',
  10,
  15,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'Talk About Hobbies',
  'Speaking practice with a clear prompt.',
  'speaking',
  'A2',
  'easy',
  'Record when ready.',
  '{"prompt":"Talk about two hobbies. Say how often you do them and why you like them.","expectedDuration":30,"mode":"answer","evaluation":{"pronunciation":true,"fluency":true,"grammar":true,"vocabulary":true,"coherence":false}}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1543269865-cbf427effbad?w=800&q=80&auto=format&fit=crop',
  10,
  10,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'Introduce Yourself',
  'Speaking practice with a clear prompt.',
  'speaking',
  'A1',
  'easy',
  'Record when ready.',
  '{"prompt":"Read aloud clearly, then try from memory.","expectedDuration":30,"mode":"read_aloud","referenceText":"Hello, my name is Alex. I am from Brazil. I am a student. I like English classes.","evaluation":{"pronunciation":true,"fluency":true,"grammar":false,"vocabulary":false,"coherence":false}}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=800&q=80&auto=format&fit=crop',
  10,
  10,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'Persuade a Friend',
  'Speaking practice with a clear prompt.',
  'speaking',
  'B2',
  'hard',
  'Record when ready.',
  '{"prompt":"Persuade a friend to join an evening English club. Give three good reasons.","expectedDuration":60,"mode":"answer","evaluation":{"pronunciation":true,"fluency":true,"grammar":true,"vocabulary":true,"coherence":true}}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=800&q=80&auto=format&fit=crop',
  10,
  20,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'Connectors Challenge',
  'Open cloze with advanced linkers.',
  'fill_blank',
  'C1',
  'hard',
  'One word per gap.',
  '{"items":[{"id":"1","sentence":"_____ the delay, the launch succeeded.","answer":"Despite"},{"id":"2","sentence":"She left early _____ as to catch the train.","answer":"so"},{"id":"3","sentence":"The plan failed; _____, we learned a lot.","answer":"nevertheless","alternatives":["however"]},{"id":"4","sentence":"_____ had we arrived when it started raining.","answer":"Hardly"},{"id":"5","sentence":"He acts _____ he owns the place.","answer":"as"},{"id":"6","sentence":"I agree, _____ I still have doubts.","answer":"although","alternatives":["though"]},{"id":"7","sentence":"Take a map _____ you get lost.","answer":"in"},{"id":"8","sentence":"The more you practice, _____ better you get.","answer":"the"}],"explanation":"Focus on linkers and fixed patterns."}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&q=80&auto=format&fit=crop',
  12,
  20,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'Perfect Gaps',
  'Present perfect open cloze.',
  'fill_blank',
  'B1',
  'medium',
  'One word per gap.',
  '{"items":[{"id":"1","sentence":"I have _____ finished the report.","answer":"already"},{"id":"2","sentence":"She hasn’t called _____.","answer":"yet"},{"id":"3","sentence":"We have lived here _____ 2019.","answer":"since"},{"id":"4","sentence":"They have been friends _____ ten years.","answer":"for"},{"id":"5","sentence":"_____ you ever tried sushi?","answer":"Have"},{"id":"6","sentence":"He has _____ left.","answer":"just"},{"id":"7","sentence":"I haven’t seen her _____ Monday.","answer":"since"}],"explanation":"already / yet / since / for / just / have"}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&q=80&auto=format&fit=crop',
  10,
  15,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'Yesterday Gaps',
  'Past simple cloze for everyday stories.',
  'fill_blank',
  'A2',
  'easy',
  'One word per gap.',
  '{"items":[{"id":"1","sentence":"I _____ to the cinema yesterday.","answer":"went"},{"id":"2","sentence":"She _____ a great movie.","answer":"watched","alternatives":["saw"]},{"id":"3","sentence":"We _____ pizza after the film.","answer":"ate","alternatives":["had"]},{"id":"4","sentence":"It _____ late when we left.","answer":"was"},{"id":"5","sentence":"They _____ not take a taxi.","answer":"did"},{"id":"6","sentence":"_____ you enjoy the evening?","answer":"Did"}],"explanation":"Past simple forms."}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&q=80&auto=format&fit=crop',
  8,
  10,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'Be Gaps',
  'Am / is / are open cloze.',
  'fill_blank',
  'A1',
  'easy',
  'One word per gap.',
  '{"items":[{"id":"1","sentence":"I _____ a student.","answer":"am"},{"id":"2","sentence":"She _____ happy today.","answer":"is"},{"id":"3","sentence":"They _____ my friends.","answer":"are"},{"id":"4","sentence":"He _____ from Brazil.","answer":"is"},{"id":"5","sentence":"We _____ in the classroom.","answer":"are"},{"id":"6","sentence":"_____ you ready?","answer":"Are"}],"explanation":"Verb to be."}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800&q=80&auto=format&fit=crop',
  6,
  10,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'News Passive Gaps',
  'Passive voice in short news lines.',
  'fill_blank',
  'B2',
  'hard',
  'One word per gap.',
  '{"items":[{"id":"1","sentence":"The letter was _____ yesterday.","answer":"sent"},{"id":"2","sentence":"The bridge is being _____.","answer":"repaired","alternatives":["built"]},{"id":"3","sentence":"The thief was _____ by police.","answer":"caught"},{"id":"4","sentence":"English is _____ all over the world.","answer":"spoken"},{"id":"5","sentence":"The results will be _____ on Friday.","answer":"published","alternatives":["announced"]},{"id":"6","sentence":"The film was _____ by a new director.","answer":"directed"}],"explanation":"Passive: be + past participle."}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=800&q=80&auto=format&fit=crop',
  10,
  20,
  true,
  true,
  null
);

-- Media catalog (requires migration 20260822150000_allow_media_activity_types.sql)
insert into public.activities (
  id, title, description, type, level, difficulty, instructions, content,
  audio_url, image_url, duration, points, is_published, is_system, created_by
) values
(
  gen_random_uuid(),
  'Feel the Lyrics',
  'Short song clip (under 5 min) + quick comprehension quiz.',
  'music',
  'B1',
  'medium',
  'Watch the short clip (under 5 min), then answer 5 questions.',
  '{"embedUrl":"https://www.youtube-nocookie.com/embed/e-ORhEE9VVg","questions":[{"question":"What should you listen for first in a song?","options":["The chorus / repeated words","Only the drums","Silence only","The video ads"],"correctIndex":0,"explanation":"Choruses repeat key vocabulary and are easier to catch."},{"question":"A useful strategy is…","options":["Replay a short part slowly","Never rewind","Ignore the lyrics","Mute the song"],"correctIndex":0},{"question":"“Feel” in many lyrics often means…","options":["An emotion","A suitcase","A Wi-Fi code","A passport"],"correctIndex":0},{"question":"Singing along quietly can help…","options":["Pronunciation and rhythm","Only typing speed","Deleting words","Closing the tab"],"correctIndex":0},{"question":"Before the quiz, you should…","options":["Listen at least once carefully","Skip the audio","Guess randomly","Close your eyes forever"],"correctIndex":0}],"prompt":"What should you listen for first in a song?","options":["The chorus / repeated words","Only the drums","Silence only","The video ads"],"correctIndex":0}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&q=80&auto=format&fit=crop',
  5,
  15,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'Chorus Fill-In',
  'Short song clip (under 5 min) + quick comprehension quiz.',
  'music',
  'A2',
  'easy',
  'Watch the short clip (under 5 min), then answer 5 questions.',
  '{"embedUrl":"https://www.youtube-nocookie.com/embed/hT_nvWreIhg","questions":[{"question":"What should you listen for first in a song?","options":["The chorus / repeated words","Only the drums","Silence only","The video ads"],"correctIndex":0,"explanation":"Choruses repeat key vocabulary and are easier to catch."},{"question":"A useful strategy is…","options":["Replay a short part slowly","Never rewind","Ignore the lyrics","Mute the song"],"correctIndex":0},{"question":"“Feel” in many lyrics often means…","options":["An emotion","A suitcase","A Wi-Fi code","A passport"],"correctIndex":0},{"question":"Singing along quietly can help…","options":["Pronunciation and rhythm","Only typing speed","Deleting words","Closing the tab"],"correctIndex":0},{"question":"Before the quiz, you should…","options":["Listen at least once carefully","Skip the audio","Guess randomly","Close your eyes forever"],"correctIndex":0}],"prompt":"What should you listen for first in a song?","options":["The chorus / repeated words","Only the drums","Silence only","The video ads"],"correctIndex":0}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&q=80&auto=format&fit=crop',
  5,
  15,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'Coffee Shop English',
  'Short English video (under 5 min) + quick quiz.',
  'video',
  'B1',
  'medium',
  'Watch the short clip (under 5 min), then answer 5 questions.',
  '{"embedUrl":"https://www.youtube-nocookie.com/embed/v9EWItbdvVs","questions":[{"question":"What should you do first?","options":["Watch for the main idea","Skip the video","Mute forever","Close the tab"],"correctIndex":0,"explanation":"Gist first, then details — Cambridge-style listening."},{"question":"If speech is fast, you can…","options":["Replay and slow the clip","Give up immediately","Ignore visuals","Skip all questions"],"correctIndex":0},{"question":"Subtitles help you…","options":["Connect sound and spelling","Avoid English","Stop listening","Delete audio"],"correctIndex":0},{"question":"Key vocabulary often appears…","options":["More than once","Never","Only in ads","Only in the title"],"correctIndex":0},{"question":"After watching, check…","options":["What you understood","Only the thumbnail","Only the URL","Nothing"],"correctIndex":0}],"prompt":"What should you do first?","options":["Watch for the main idea","Skip the video","Mute forever","Close the tab"],"correctIndex":0}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80&auto=format&fit=crop',
  5,
  15,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'Café Order Practice',
  'Short English video (under 5 min) + quick quiz.',
  'video',
  'A2',
  'easy',
  'Watch the short clip (under 5 min), then answer 5 questions.',
  '{"embedUrl":"https://www.youtube-nocookie.com/embed/1dxXd7JNu7g","questions":[{"question":"What should you do first?","options":["Watch for the main idea","Skip the video","Mute forever","Close the tab"],"correctIndex":0,"explanation":"Gist first, then details — Cambridge-style listening."},{"question":"If speech is fast, you can…","options":["Replay and slow the clip","Give up immediately","Ignore visuals","Skip all questions"],"correctIndex":0},{"question":"Subtitles help you…","options":["Connect sound and spelling","Avoid English","Stop listening","Delete audio"],"correctIndex":0},{"question":"Key vocabulary often appears…","options":["More than once","Never","Only in ads","Only in the title"],"correctIndex":0},{"question":"After watching, check…","options":["What you understood","Only the thumbnail","Only the URL","Nothing"],"correctIndex":0}],"prompt":"What should you do first?","options":["Watch for the main idea","Skip the video","Mute forever","Close the tab"],"correctIndex":0}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=800&q=80&auto=format&fit=crop',
  5,
  15,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'Ordering Coffee',
  'Short café clip (under 5 min): tap words, then complete the gap.',
  'video',
  'A2',
  'easy',
  'Watch (under 5 min) → tap words → complete the gap → listen again.',
  '{"mode":"interactive","embedUrl":"https://www.youtube-nocookie.com/embed/IxbXVxYKVRw","transcript":[{"start":0,"end":4,"text":"Good morning. Welcome to our cafe. What are you in the mood for today?"},{"start":4,"end":8,"text":"I''d like a latte style coffee, please. Something smooth."},{"start":8,"end":12,"text":"What size? Short, tall, grande, or venti?"},{"start":12,"end":16,"text":"I''ll go with a grande, with almond milk and a hint of vanilla."}],"glossary":{"latte":{"meaning":"Espresso with steamed milk — a popular café drink.","pronunciation":"/ˈlɑːteɪ/","kind":"meaning"},"grande":{"meaning":"A medium-large size in many cafés (bigger than tall).","pronunciation":"/ˈɡrɑːndeɪ/","kind":"meaning"},"almond":{"meaning":"A nut; “almond milk” is a dairy-free milk option.","pronunciation":"/ˈɑːmənd/","kind":"sound"},"vanilla":{"meaning":"A sweet flavour often added to coffee drinks.","pronunciation":"/vəˈnɪlə/","kind":"meaning"}},"gap":{"sentence":"I''ll go with a ______, with almond milk and vanilla.","options":["grande","short","venti"],"correctIndex":0,"explanation":"The customer chooses a grande size."}}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=800&q=80&auto=format&fit=crop',
  5,
  15,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'At the Airport',
  'Short travel English clip (under 5 min) with tap-to-learn transcript.',
  'video',
  'A2',
  'easy',
  'Watch (under 5 min) → explore words → complete the gap → listen again.',
  '{"mode":"interactive","embedUrl":"https://www.youtube-nocookie.com/embed/l3IC2r_k08U","transcript":[{"start":0,"end":4,"text":"Good morning. I have a reservation."},{"start":4,"end":8,"text":"May I see your passport, please?"},{"start":8,"end":12,"text":"Of course. Here you are."},{"start":12,"end":16,"text":"Thank you. Enjoy your flight."}],"glossary":{"reservation":{"meaning":"A booking you made in advance.","pronunciation":"/ˌrezəˈveɪʃn/","kind":"meaning"},"passport":{"meaning":"Official travel document with your photo.","pronunciation":"/ˈpɑːspɔːt/","kind":"sound"},"May":{"meaning":"Polite word for asking permission.","pronunciation":"/meɪ/","kind":"explain"},"flight":{"meaning":"A journey by plane.","pronunciation":"/flaɪt/","kind":"meaning"}},"gap":{"sentence":"May I see your ______, please?","options":["passport","ticket","suitcase"],"correctIndex":0,"explanation":"The agent asks to see the passenger’s passport."}}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1492619375914-88005aa9e8fb?w=800&q=80&auto=format&fit=crop',
  5,
  15,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'Quick Quiz Arena',
  'Short practice round with a focused quiz.',
  'game',
  'A2',
  'easy',
  'Watch the short clip (under 5 min), then answer 5 questions.',
  '{"embedUrl":"https://www.youtube-nocookie.com/embed/1dxXd7JNu7g","questions":[{"question":"In a language game, you should…","options":["Read each question carefully","Tap the first option always","Ignore feedback","Quit immediately"],"correctIndex":0},{"question":"Wrong answers help you…","options":["Notice gaps and try again","Delete English","Stop learning","Skip forever"],"correctIndex":0},{"question":"A good pace is…","options":["Steady and focused","As fast as possible with no reading","Never checking","Only guessing"],"correctIndex":0},{"question":"Vocabulary in games is useful because…","options":["It appears in real contexts","It replaces sleep","It is never spoken","It deletes grammar"],"correctIndex":0},{"question":"After finishing, you should…","options":["Review mistakes briefly","Forget everything","Close without looking","Never replay"],"correctIndex":0}],"prompt":"In a language game, you should…","options":["Read each question carefully","Tap the first option always","Ignore feedback","Quit immediately"],"correctIndex":0}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&q=80&auto=format&fit=crop',
  5,
  15,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'Grammar Duel',
  'Short practice round with a focused quiz.',
  'game',
  'B1',
  'medium',
  'Watch the short clip (under 5 min), then answer 5 questions.',
  '{"embedUrl":"https://www.youtube-nocookie.com/embed/1dxXd7JNu7g","questions":[{"question":"In a language game, you should…","options":["Read each question carefully","Tap the first option always","Ignore feedback","Quit immediately"],"correctIndex":0},{"question":"Wrong answers help you…","options":["Notice gaps and try again","Delete English","Stop learning","Skip forever"],"correctIndex":0},{"question":"A good pace is…","options":["Steady and focused","As fast as possible with no reading","Never checking","Only guessing"],"correctIndex":0},{"question":"Vocabulary in games is useful because…","options":["It appears in real contexts","It replaces sleep","It is never spoken","It deletes grammar"],"correctIndex":0},{"question":"After finishing, you should…","options":["Review mistakes briefly","Forget everything","Close without looking","Never replay"],"correctIndex":0}],"prompt":"In a language game, you should…","options":["Read each question carefully","Tap the first option always","Ignore feedback","Quit immediately"],"correctIndex":0}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1553481187-be93c21490a9?w=800&q=80&auto=format&fit=crop',
  5,
  15,
  true,
  true,
  null
),
(
  gen_random_uuid(),
  'Vocabulary Battle',
  'Short practice round with a focused quiz.',
  'game',
  'B1',
  'medium',
  'Watch the short clip (under 5 min), then answer 5 questions.',
  '{"embedUrl":"https://www.youtube-nocookie.com/embed/1dxXd7JNu7g","questions":[{"question":"In a language game, you should…","options":["Read each question carefully","Tap the first option always","Ignore feedback","Quit immediately"],"correctIndex":0},{"question":"Wrong answers help you…","options":["Notice gaps and try again","Delete English","Stop learning","Skip forever"],"correctIndex":0},{"question":"A good pace is…","options":["Steady and focused","As fast as possible with no reading","Never checking","Only guessing"],"correctIndex":0},{"question":"Vocabulary in games is useful because…","options":["It appears in real contexts","It replaces sleep","It is never spoken","It deletes grammar"],"correctIndex":0},{"question":"After finishing, you should…","options":["Review mistakes briefly","Forget everything","Close without looking","Never replay"],"correctIndex":0}],"prompt":"In a language game, you should…","options":["Read each question carefully","Tap the first option always","Ignore feedback","Quit immediately"],"correctIndex":0}'::jsonb,
  null,
  'https://images.unsplash.com/photo-1606326608606-aa0b62935f2b?w=800&q=80&auto=format&fit=crop',
  5,
  15,
  true,
  true,
  null
);
